[package]
name = "email_newsletter_server"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
actix-web = "4.12.1"
reqwest = "0.13.2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
